# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# changelog header
header = """
# Changelog\n
"""

# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/catppuccin/nix/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | striptags | trim | upper_first }}

  {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") -%}
    - **{{ commit.scope }}**: {{ commit.message | trim }}\
      {%- if commit.github.username %} by (@{{ commit.github.username }}){% endif %}
  {% endfor -%}

  {% for commit in commits -%}
    {% if commit.scope -%}
    {% else -%}
      - {{ commit.message | trim }}\
        {% if commit.github.username %} by (@{{ commit.github.username }}){% endif %}
    {% endif -%}
  {% endfor -%}
{% endfor -%}

{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ### New Contributors

{% endif -%}

{% for contributor in github.contributors | filter(attribute="username") | filter(attribute="is_first_time", value=true) | sort(attribute="username") -%}
  * (@{{ contributor.username }}) made their first contribution\
    {% if contributor.pr_number %} in (#{{ contributor.pr_number }}){% endif %}
{% endfor %}\n
"""

footer = """
<!-- generated by git-cliff -->
"""

# remove the leading and trailing s
trim = true

# postprocessors
postprocessors = [
  # issues/PR
  { pattern = "\\(#([0-9]+)\\)", replace = "[#${1}](https://github.com/catppuccin/nix/issues/${1})" },
  # commits
  { pattern = "([a-f0-9]{7})", replace = "[${1}](https://github.com/catppuccin/nix/commit/${1})" },
  # github users
  { pattern = "\\(@([a-zA-Z0-9-_]+)\\)", replace = "[@${1}](https://github.com/${1})" }
]

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true

# filter out the commits that are not conventional
filter_unconventional = true

# process each line of a commit as an individual commit
split_commits = false

# regex for preprocessing the commit messages
commit_preprocessors = [
  # remove issue numbers
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

# regex for parsing and grouping commits
commit_parsers = [
  # this commit message isn't properly escaped
  { sha = "aa3a9816e9d6bc361ab1156f1e7a850fc0b5f4f8", skip = true },

  # ignore bot PRs
  { field = "author.name", pattern = "\\[bot\\]", skip = true },

  # ignore some commits not matched by the above
  { message = "^docs: update docs for ([a-f0-9]{7})?$", skip = true },
  { message = "^style: format ([a-f0-9]{7})?$", skip = true },

  # regular matches
  { message = "^(.*)!:", group = "<!-- 0 -->🚨 Breaking Changes" },
  { message = "^feat", group = "<!-- 1 -->🚀 Features" },
  { message = "^fix", group = "<!-- 2 -->🐛 Bug Fixes" },
  { message = "^revert", group = "<!-- 3 --> ⏪ Reverted"},
  { message = "^docs", group = "<!-- 4 -->📚 Documentation" },
  { message = "^refactor", group = "<!-- 5 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 6 -->🎨 Styling" },
  { message = "^ci", group = "<!-- 7 -->🔧 CI" },
  { message = "^chore", group = "<!-- 8 -->⚙️  Miscellaneous Tasks" }
]

# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false

# filter out the commits that are not matched by commit parsers
filter_commits = true

# regex for matching git tags
tag_pattern = "v[0-9].*.*"

# regex for skipping tags
skip_tags = ""

# regex for ignoring tags
ignore_tags = ""

# sort the tags topologically
topo_order = false

# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"

# limit the number of commits included in the changelog.
# limit_commits = 42
