# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "3c808cbb4f9c87be43ba5241bc57373c793d2f17";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "3c808cbb4f9c87be43ba5241bc57373c793d2f17";
      fetchSubmodules = false;
      sha256 = "sha256-w9XVtEe7TqzxxGUCDUR9BFkzLZjG8XrplXJ3lX6f+x0=";
    };
    date = "2022-09-27";
  };
  bat = {
    pname = "bat";
    version = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
      fetchSubmodules = false;
      sha256 = "sha256-6WVKQErGdaqb++oaXnY3i6/GuH2FhTgK0v4TN4Y0Wbw=";
    };
    date = "2022-11-10";
  };
  bottom = {
    pname = "bottom";
    version = "c0efe9025f62f618a407999d89b04a231ba99c92";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bottom";
      rev = "c0efe9025f62f618a407999d89b04a231ba99c92";
      fetchSubmodules = false;
      sha256 = "sha256-VaHX2I/Gn82wJWzybpWNqU3dPi3206xItOlt0iF6VVQ=";
    };
    date = "2022-12-30";
  };
  btop = {
    pname = "btop";
    version = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
      fetchSubmodules = false;
      sha256 = "sha256-jodJl4f2T9ViNqsY9fk8IV62CrpC5hy7WK3aRpu70Cs=";
    };
    date = "2023-10-07";
  };
  fish = {
    pname = "fish";
    version = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
      fetchSubmodules = false;
      sha256 = "sha256-Dc/zdxfzAUM5NX8PxzfljRbYvO9f9syuLO8yBr+R3qg=";
    };
    date = "2023-11-02";
  };
  glamour = {
    pname = "glamour";
    version = "3ef2c9533b6d3c4d6309a850765500179cf32d1c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "glamour";
      rev = "3ef2c9533b6d3c4d6309a850765500179cf32d1c";
      fetchSubmodules = false;
      sha256 = "sha256-HD7g9unpRYLIj00FOqLiiInMYgGgYujjvAeYOa+V76Y=";
    };
    date = "2023-05-01";
  };
  grub = {
    pname = "grub";
    version = "803c5df0e83aba61668777bb96d90ab8f6847106";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "grub";
      rev = "803c5df0e83aba61668777bb96d90ab8f6847106";
      fetchSubmodules = false;
      sha256 = "sha256-/bSolCta8GCZ4lP0u5NVqYQ9Y3ZooYCNdTwORNvR7M0=";
    };
    date = "2022-12-29";
  };
  gtk = {
    pname = "gtk";
    version = "9082969c1c33b0dc8d8e9a8a241d029f2d864599";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gtk";
      rev = "9082969c1c33b0dc8d8e9a8a241d029f2d864599";
      fetchSubmodules = false;
      sha256 = "sha256-95H/jWbaDYX+tdhLODMcKunh2EXelf5Wd/vG9ZKFdSc=";
    };
    date = "2023-10-05";
  };
  helix = {
    pname = "helix";
    version = "8313c7250fcbbb22c6680db332669073ec6b28c2";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "helix";
      rev = "8313c7250fcbbb22c6680db332669073ec6b28c2";
      fetchSubmodules = false;
      sha256 = "sha256-qEXhj/Mpm+aqThqEq5DlPJD8nsbPov9CNMgG9s4E02g=";
    };
    date = "2023-10-20";
  };
  kitty = {
    pname = "kitty";
    version = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
      fetchSubmodules = false;
      sha256 = "sha256-uZSx+fuzcW//5/FtW98q7G4xRRjJjD5aQMbvJ4cs94U=";
    };
    date = "2023-06-09";
  };
  lazygit = {
    pname = "lazygit";
    version = "0543c28e8af1a935f8c512ad9451facbcc17d8a8";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "lazygit";
      rev = "0543c28e8af1a935f8c512ad9451facbcc17d8a8";
      fetchSubmodules = false;
      sha256 = "sha256-OVihY5E+elPKag2H4RyWiSv+MdIqHtfGNM3/1u2ik6U=";
    };
    date = "2023-09-19";
  };
  mako = {
    pname = "mako";
    version = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mako";
      rev = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
      fetchSubmodules = false;
      sha256 = "sha256-nUzWkQVsIH4rrCFSP87mXAka6P+Td2ifNbTuP7NM/SQ=";
    };
    date = "2023-08-12";
  };
  micro = {
    pname = "micro";
    version = "ed8ef015f97c357575b5013e18042c9faa6c068a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "micro";
      rev = "ed8ef015f97c357575b5013e18042c9faa6c068a";
      fetchSubmodules = false;
      sha256 = "sha256-/JwZ+5bLYjZWcV5vH22daLqVWbyJelqRyGa7V0b7EG8=";
    };
    date = "2022-09-27";
  };
  neovim = {
    pname = "neovim";
    version = "40dc9f0621c55bd40da4ad0731fac44d15bb393a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "40dc9f0621c55bd40da4ad0731fac44d15bb393a";
      fetchSubmodules = false;
      sha256 = "sha256-m1SYlSUVO9BbxUzPZ1VFkfCSHVTYSp65TX3mUm+kjeo=";
    };
    date = "2023-11-01";
  };
  polybar = {
    pname = "polybar";
    version = "9ee66f83335404186ce979bac32fcf3cd047396a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "polybar";
      rev = "9ee66f83335404186ce979bac32fcf3cd047396a";
      fetchSubmodules = false;
      sha256 = "sha256-bUbSgMg/sa2faeEUZo80GNmhOX3wn2jLzfA9neF8ERA=";
    };
    date = "2022-10-05";
  };
  starship = {
    pname = "starship";
    version = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "starship";
      rev = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
      fetchSubmodules = false;
      sha256 = "sha256-nsRuxQFKbQkyEI4TXgvAjcroVdG+heKX5Pauq/4Ota0=";
    };
    date = "2023-07-13";
  };
  sway = {
    pname = "sway";
    version = "c976222e5cacbba7946fb82163944924bd5fac12";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "sway";
      rev = "c976222e5cacbba7946fb82163944924bd5fac12";
      fetchSubmodules = false;
      sha256 = "sha256-VEyjHFjNFQQB20NGciO8y2m/rWkASzQZQekzGZ88pLg=";
    };
    date = "2023-08-20";
  };
  swaylock = {
    pname = "swaylock";
    version = "9b88d9e866c044d47c98046ee6c8d6de2546cf82";
    src = fetchFromGitHub {
      owner = "remiposo";
      repo = "swaylock";
      rev = "9b88d9e866c044d47c98046ee6c8d6de2546cf82";
      fetchSubmodules = false;
      sha256 = "sha256-v2op7V52VYqzY9govnfkgmF7ybRRlPkohgnrUWDjItI=";
    };
    date = "2023-02-10";
  };
  tmux = {
    pname = "tmux";
    version = "47e33044b4b47b1c1faca1e42508fc92be12131a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tmux";
      rev = "47e33044b4b47b1c1faca1e42508fc92be12131a";
      fetchSubmodules = false;
      sha256 = "sha256-kn3kf7eiiwXj57tgA7fs5N2+B2r441OtBlM8IBBLl4I=";
    };
    date = "2023-11-01";
  };
}
