# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "071d73effddac392d5b9b8cd5b4b527a6cf289f9";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "071d73effddac392d5b9b8cd5b4b527a6cf289f9";
      fetchSubmodules = false;
      sha256 = "sha256-HiIYxTlif5Lbl9BAvPsnXp8WAexL8YuohMDd/eCJVQ8=";
    };
    date = "2024-02-26";
  };
  bat = {
    pname = "bat";
    version = "a875b71dc5514b2eae9174b0591ef421887aa99f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "a875b71dc5514b2eae9174b0591ef421887aa99f";
      fetchSubmodules = false;
      sha256 = "sha256-PWX8LR3xTgNBUpk+xBIGpEBQCNJHre8cRX4OTSWkZvs=";
    };
    date = "2024-03-08";
  };
  bottom = {
    pname = "bottom";
    version = "c0efe9025f62f618a407999d89b04a231ba99c92";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bottom";
      rev = "c0efe9025f62f618a407999d89b04a231ba99c92";
      fetchSubmodules = false;
      sha256 = "sha256-VaHX2I/Gn82wJWzybpWNqU3dPi3206xItOlt0iF6VVQ=";
    };
    date = "2022-12-30";
  };
  btop = {
    pname = "btop";
    version = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
      fetchSubmodules = false;
      sha256 = "sha256-jodJl4f2T9ViNqsY9fk8IV62CrpC5hy7WK3aRpu70Cs=";
    };
    date = "2023-10-07";
  };
  fish = {
    pname = "fish";
    version = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
      fetchSubmodules = false;
      sha256 = "sha256-Dc/zdxfzAUM5NX8PxzfljRbYvO9f9syuLO8yBr+R3qg=";
    };
    date = "2023-11-02";
  };
  glamour = {
    pname = "glamour";
    version = "3ef2c9533b6d3c4d6309a850765500179cf32d1c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "glamour";
      rev = "3ef2c9533b6d3c4d6309a850765500179cf32d1c";
      fetchSubmodules = false;
      sha256 = "sha256-HD7g9unpRYLIj00FOqLiiInMYgGgYujjvAeYOa+V76Y=";
    };
    date = "2023-05-01";
  };
  grub = {
    pname = "grub";
    version = "88f6124757331fd3a37c8a69473021389b7663ad";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "grub";
      rev = "88f6124757331fd3a37c8a69473021389b7663ad";
      fetchSubmodules = false;
      sha256 = "sha256-e8XFWebd/GyX44WQI06Cx6sOduCZc5z7/YhweVQGMGY=";
    };
    date = "2024-03-07";
  };
  gtk = {
    pname = "gtk";
    version = "26b0d12b1b3f0d3266581f08e428d335eba8b2b2";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gtk";
      rev = "26b0d12b1b3f0d3266581f08e428d335eba8b2b2";
      fetchSubmodules = false;
      sha256 = "sha256-Ok/lv9VoZ1CpQnmq4JiC9TgOyxPZl4hqozoerIczuQQ=";
    };
    date = "2024-02-24";
  };
  helix = {
    pname = "helix";
    version = "b3b058b85340a023f51da17cfa3df82ae4ac3828";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "helix";
      rev = "b3b058b85340a023f51da17cfa3df82ae4ac3828";
      fetchSubmodules = false;
      sha256 = "sha256-2j90zbSDEEJaSZ/YF9IbcjB/4cOcuAAqmwP4mA/q30o=";
    };
    date = "2024-02-25";
  };
  hyprland = {
    pname = "hyprland";
    version = "fc228737d3d0c12e34a7fa155a0fc3192e5e4017";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "hyprland";
      rev = "fc228737d3d0c12e34a7fa155a0fc3192e5e4017";
      fetchSubmodules = false;
      sha256 = "sha256-9BhZq9J1LmHfAPBqOr64chiAEzS+YV6zqe9ma95V3no=";
    };
    date = "2023-12-15";
  };
  kitty = {
    pname = "kitty";
    version = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
      fetchSubmodules = false;
      sha256 = "sha256-mRFa+40fuJCUrR1o4zMi7AlgjRtFmii4fNsQyD8hIjM=";
    };
    date = "2024-01-10";
  };
  lazygit = {
    pname = "lazygit";
    version = "a544cef9a18c3a94e0344281e0ddcf99a18a8ede";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "lazygit";
      rev = "a544cef9a18c3a94e0344281e0ddcf99a18a8ede";
      fetchSubmodules = false;
      sha256 = "sha256-gM0HplHhcpvtpmIVdlX/p59h0v+ihKEidS1imqPYlBg=";
    };
    date = "2024-02-04";
  };
  mako = {
    pname = "mako";
    version = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mako";
      rev = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
      fetchSubmodules = false;
      sha256 = "sha256-nUzWkQVsIH4rrCFSP87mXAka6P+Td2ifNbTuP7NM/SQ=";
    };
    date = "2023-08-12";
  };
  micro = {
    pname = "micro";
    version = "ed8ef015f97c357575b5013e18042c9faa6c068a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "micro";
      rev = "ed8ef015f97c357575b5013e18042c9faa6c068a";
      fetchSubmodules = false;
      sha256 = "sha256-/JwZ+5bLYjZWcV5vH22daLqVWbyJelqRyGa7V0b7EG8=";
    };
    date = "2022-09-27";
  };
  neovim = {
    pname = "neovim";
    version = "045e3499d9ec8d84635fb08877ae44fd33f6a38d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "045e3499d9ec8d84635fb08877ae44fd33f6a38d";
      fetchSubmodules = false;
      sha256 = "sha256-arOnsTg+q14qMI24QrcA/ca3tU7qxhoenRksRk1xBtE=";
    };
    date = "2024-03-05";
  };
  polybar = {
    pname = "polybar";
    version = "989420b24e1f651b176c9d6083ad7c3b90a27f8b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "polybar";
      rev = "989420b24e1f651b176c9d6083ad7c3b90a27f8b";
      fetchSubmodules = false;
      sha256 = "sha256-2fNqE5r6yMKH6h+rjXF/lnUjK2xc3uO+swCS4oqGenM=";
    };
    date = "2024-02-03";
  };
  starship = {
    pname = "starship";
    version = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "starship";
      rev = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
      fetchSubmodules = false;
      sha256 = "sha256-nsRuxQFKbQkyEI4TXgvAjcroVdG+heKX5Pauq/4Ota0=";
    };
    date = "2023-07-13";
  };
  sway = {
    pname = "sway";
    version = "c7e54561a2539024020837f23068f70c6d2ae424";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "sway";
      rev = "c7e54561a2539024020837f23068f70c6d2ae424";
      fetchSubmodules = false;
      sha256 = "sha256-DmwszeXRWt7LkCP8xqRIOgr/U3soTi7pbNHKTUCorcw=";
    };
    date = "2023-12-20";
  };
  tmux = {
    pname = "tmux";
    version = "32df6db4b44ce901b7a9a10d1299d507dd218641";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tmux";
      rev = "32df6db4b44ce901b7a9a10d1299d507dd218641";
      fetchSubmodules = false;
      sha256 = "sha256-LJWwTy9raWY2T0kZeP95aC0Jw+WA2eB6Rg0pLgzYHS8=";
    };
    date = "2024-03-07";
  };
  zathura = {
    pname = "zathura";
    version = "1bda9d8274dd327b7931886ef0c5c1eb33903814";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zathura";
      rev = "1bda9d8274dd327b7931886ef0c5c1eb33903814";
      fetchSubmodules = false;
      sha256 = "sha256-HWOc5tnVgU/HUcVcIXACeuu3RDH1pHO/8DQRsWqumIA=";
    };
    date = "2024-02-12";
  };
}
