name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.lock'
      - '**.nix'
      - 'pkgs/**'

      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.lock'
      - '**.nix'
      - 'pkgs/**'

      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  packages:
    name: Build Packages (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Stop pinning Nix when 2.26 is released
          # https://hydra.nixos.org/eval/1811064
          - os: macos-latest
            nix-package-url: https://hydra.nixos.org/build/285626775/download/1/nix-2.26.0pre19700101_bcb92a5-aarch64-darwin.tar.xz

          - os: macos-13
            nix-package-url: https://hydra.nixos.org/build/285626866/download/1/nix-2.26.0pre19700101_bcb92a5-x86_64-darwin.tar.xz

          - os: ubuntu-latest
            nix-package-url: https://hydra.nixos.org/build/285626679/download/1/nix-2.26.0pre19700101_bcb92a5-x86_64-linux.tar.xz

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          nix-package-url: ${{ matrix.nix-package-url }}

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: catppuccin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run build
        run: |
          nix run './dev#build-hydra-job' -- 'packages'

  modules:
    name: Test Modules (${{ matrix.os }})
    needs: packages

    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Stop pinning Nix when 2.26 is released
          # https://hydra.nixos.org/eval/1811064
          - os: macos-latest
            nix-package-url: https://hydra.nixos.org/build/285626775/download/1/nix-2.26.0pre19700101_bcb92a5-aarch64-darwin.tar.xz

          - os: ubuntu-latest
            nix-package-url: https://hydra.nixos.org/build/285626679/download/1/nix-2.26.0pre19700101_bcb92a5-x86_64-linux.tar.xz

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          nix-package-url: ${{ matrix.nix-package-url }}

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: catppuccin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run tests
        run: |
          nix run './dev#build-hydra-job' -- 'checks'

  release-gate:
    name: Release Gate
    needs: [ modules, packages ]

    runs-on: ubuntu-latest

    steps:
      - name: Exit with error
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
